version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8545:8545"
    environment:
      - NODE_ENV=development
      - PORT=8545
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
  levin_ai:
    build: ./levin_ai
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
